### ISSUE TITLE
Synchronize tasks between Gogs and kanboard

### ISSUE THREAD

**Issue by baby-gnu** [kanboard/plugin-gogs-webhook#1]
Hello,

We are users of redmine + [redmine_backlog](https://github.com/backlogs/redmine_backlogs) and give a try to Gogs + kanboard.

Actually in kanboard, a commit in Gogs can move a task.

in our team, we avoid moving tasks automatically to do it in front of everybody during the scrum, so closing a task in kanboard should close the task in Gogs.

So we need some kind of task synchronisation, does it seems possible?

Regards.

**Comment by fguillot** [comment]
Unfortunately, the webhook system and the api of Gogs are pretty limited at the moment.

**Comment by AlgyTaylor** [comment]
It looks like the gogs webhooks have been fleshed out somewhat over the past year:
https://github.com/gogits/go-gogs-client/wiki/Repositories-Webhooks

Do you think it'd be possible to allow a workflow like:
- User creates issue on gogs
- Kanboard creates task on board from webhook issue
- I comment on a task in kanboard, it adds those comments to Gogs (and perhaps vice-versa).  It'd be really helpful too if you could combine automatic actions here, so the automatic "xxx moved to column "priority" would be copied over to gogs
- I close an issue on Gogs, the ticket gets closed on kanboard  (not the other way round, those

I think that would make gogs/kanboard a really incredible pair of tools for software development.  You'd be able to completely capture the software development flow between those two, I think ...

**Comment by fguillot** [comment]
After a quick overview of their API, that seems to be possible now.

**Comment by dakira** [comment]
It would be cool to have something similar for the Gogs-Clone Gitea. There's a lot more development happening there so that many have abandoned Gogs altogether. The API seems to be advancing more quickly, too.

**Comment by opitux** [comment]
Being able to synchronize tasks between Gitea and Kanboard would be awesome ^^
Please please please :)

**Comment by opitux** [comment]
I came back to Gogs because issues are in webhook. Issues opened and closed are handled on my side. I'll try to propose something quik but I'm learning to use git at the same time. I'll do my best :)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
