### ISSUE TITLE
Nothing happend to the task

### ISSUE THREAD

**Issue by Alsan** [kanboard/plugin-gogs-webhook#2]
Hi, just install and try your plugin, it seems working but nothing happens to the task.

I first create a task within KB, and then commit and push a modification of a file to Gogs with commit message as your example, and then checking for the push log. It's fine, there's log with resposne 'PARSED', but when I check for the task inside KB, there's nothing change.

So, what is the correct procedure to setup the hook? and what is the expected response from KB? Thanks.

**Comment by fguillot** [comment]
Did you create an automatic action in Kanboard?

**Comment by Alsan** [comment]
No, would you please point me out how can I do this? thanks.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
